### ISSUE TITLE
Internal Server Error: Cannot find module 'virtual:qwik-pwa/head'

### ISSUE THREAD

**Issue by Jauharmuhammed** [QwikDev/pwa#15]
I'm encountering an internal server error when trying to run my Qwik.js project. The error message is as follows:

> Cannot find module 'virtual:qwik-pwa/head' imported from '/Users/jauhar/Dev/qwik-pwa-sample/node_modules/@qwikdev/pwa/lib/head.qwik.js'

Any help would be greatly appreciated. Thank you!

Here is the reproduction in stackblitz : [https://stackblitz.com/edit/qwik-starter-8yhayh?file=vite.config.ts](https://stackblitz.com/edit/qwik-starter-8yhayh?file=vite.config.ts)

**Comment by Aslemammad** [comment]
Hey, Thank you so much for the issue, can we have a stackblitz reproduction?

**Comment by userquin** [comment]
@Jauharmuhammed can you try adding `"@qwikdev/pwa"` to your ts config file (`compilerOptions.types`  array)? (`"vite/client"` should be also there )
```json
"compileOptions": {
  "types": ["vite/client", "@qwikdev/pwa"]
}
```

If not using TypeScript, try adding `vite-env.d.ts` in your src folder adding triple slash reference:
```ts
// vite-env.d.ts
/// <reference types="@qwikdev/pwa" />
```

**Comment by Jauharmuhammed** [comment]
@userquin I have tried adding what you suggested, still the same issue

@Aslemammad I have added a link to the stackblitz reproduction in the description

**Comment by Aslemammad** [comment]
Thank you so much! @userquin what do you think?

**Comment by userquin** [comment]
@Jauharmuhammed you need to add `qwikPwa` plugin to Vite plugins, missing in the playground (updated link):
```ts
/**
 * This is the base config for vite.
 * When building, the adapter config is used which loads this file and extends it.
 */
import { defineConfig } from 'vite';
import { qwikVite } from '@builder.io/qwik/optimizer';
import { qwikCity } from '@builder.io/qwik-city/vite';
import tsconfigPaths from 'vite-tsconfig-paths';

import { qwikPwa } from "@qwikdev/pwa";  // <== add this import

/**
 * Note that Vite normally starts from `index.html` but the qwikCity plugin makes start at `src/entry.ssr.tsx` instead.
 */
export default defineConfig(() => {
  return {
    define: {
      // (optional) enables debugging in workbox
      'process.env.NODE_ENV': JSON.stringify('development'),
    },
    plugins: [qwikCity(), qwikVite(), tsconfigPaths(), qwikPwa({/* pwa options */})], // <== and the pwa plugin here
  };
});

**Comment by Jauharmuhammed** [comment]
I missed that, the project is running fine now, but it not PWA compatible!

The icon to install the pwa is not showing up and I tested with lighthouse as well

**Comment by userquin** [comment]
you need to add an svg (or png) to your public folder, then configure `pwaAssets` in your pwa options to build all pwa stuff, check the example where we use external pwa assets configuration file (https://github.com/QwikDev/pwa/blob/main/example/pwa-assets.config.ts): add `pwaAssets: true` (you can also inline pwa assets configuration)

**Comment by userquin** [comment]
@Aslemammad we should add pwa assets configuration to the readme file

**Comment by userquin** [comment]
@Jauharmuhammed check this page as small guide https://vite-pwa-org.netlify.app/assets-generator/integrations.html (not 100% compatible, since qwikdev pwa using custom integration)

Check also `pwaAssets` option here https://vite-pwa-org.netlify.app/assets-generator/integrations.html#pwa-assets-options

**Comment by Aslemammad** [comment]
> @Aslemammad we should add pwa assets configuration to the readme file

I agree, we should do that.
